version: '3.1'

services:
  web:
    image: aspendigital/octobercms:php7.2-apache
    ports:
      - 8100:80
    environment:
      - DB_TYPE=mysql
      - DB_HOST=mysql #DB_HOST should match the service name of the database container
      - DB_DATABASE=octobercms
      - DB_USERNAME=root
      - DB_PASSWORD=root
    volumes:
      - $PWD/../app:/var/www/html

  mysql:
    image: mysql:5.7
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=octobercms